### ISSUE TITLE
Stuck during package installation. 

### ISSUE THREAD

**Issue by cnspary** [easyops-cn/next-core#4161]
**Install Env:**
```
node version: v21.4.0
npm version: v10.2.4
@next-core/build-config-factory: 2.25.32

```
**Problem:**

when I install @next-core/build-config-factory@2.25.32 by command `npm i @next-core/build-config-factory@2.25.32 `, the **installation process gets stuck and never ends**. CPU usage will rise to 100%. Memory usage will also rise and will never be freed.

Can someone help check this out?

**Comment by cnspary** [comment]
> @next-core/build-config-factory@2.9.9
> 
> **Install Env:**
> 
> ```
> node version: v21.4.0
> npm version: v10.2.4
> @next-core/build-config-factory: 2.25.32
> 
> npm i @next-core/build-config-factory@2.25.32
> ```
> 
> **Problem:**
> 
> when I install @next-core/build-config-factory@2.25.32 by command `npm i @next-core/build-config-factory@2.25.32 `, the **installation process gets stuck and never ends**. CPU usage will rise to 100%. Memory usage will also rise and will never be freed.
> 
> Can someone help check this out?

The same problem also occurs when I use command `npm i @next-core/dev-dependencies@1.17.59`

**Comment by weareoutman** [comment]
Why would you use these packages? these are supposed to be used only in our legacy brick packages like https://github.com/easyops-cn/next-basics
